<?php

return [
    'super_admin' => [
        [
            'title' => 'إعدادات النشاط',
            'icon' => 'fas fa-cogs',
            'route' => 'business_settings.index',
            'active_routes' => ['business_settings.*'],
        ],
        [
            'title' => 'إدارة الإدمن',
            'icon' => 'fas fa-users',
            'route' => 'admins.index',
            'active_routes' => ['admins.*'],
        ],
        [
            'title' => 'الشروط والأحكام',
            'icon' => 'fas fa-file-contract',
            'route' => 'terms.index',
            'active_routes' => ['terms.*'],
        ],
        [
            'title' => 'إدارة أنواع النشاط',
            'icon' => 'fas fa-briefcase',
            'route' => 'business-types.index',
            'active_routes' => ['business-types.*'],
        ],
        [
            'title' => 'إدارة الباقات',
            'icon' => 'fas fa-box',
            'route' => 'packages.index',
            'active_routes' => ['packages.*'],
        ],
        [
            'title' => 'وسائل الدفع',
            'icon' => 'fas fa-credit-card',
            'route' => 'super.payment-methods.index',
            'active_routes' => ['payment-methods.*'],
        ],
        [
            'title' => 'إدارة الطلبات',
            'icon' => 'fas fa-file-invoice-dollar',
            'route' => 'subscriptions.index',
            'active_routes' => ['subscriptions.*'],
            'badge' => [
                'type' => 'subscription_pending',
                'class' => 'bg-yellow-500 text-black',
            ],
        ],
        [
            'title' => 'الأقسام',
            'icon' => 'fas fa-list-alt',
            'route' => 'sections.index',
            'active_routes' => ['sections.*'],
        ],
    ],

    'admin' => [
        [
            'title' => 'الرئيسية',
            'icon' => 'fas fa-home',
            'route' => 'dashboard',
            'active_routes' => ['dashboard'],
            'permission' => 'dashboard.access',
        ],

        [
            'title' => 'المنيو الإلكتروني',
            'icon' => 'fas fa-tablet-alt',
            'type' => 'dropdown',
            'id' => 'emenu-menu',
            'active_routes' => ['categories.*', 'products.*', 'sliders.*'],
            'permission' => 'emenu.access',
            'children' => [
                [
                    'title' => 'الفئات',
                    'icon' => 'far fa-circle',
                    'route' => 'categories.index',
                    'active_routes' => ['categories.*'],
                    'permission' => 'categories.access',
                ],
                [
                    'title' => 'المنتجات',
                    'icon' => 'far fa-circle',
                    'route' => 'products.index',
                    'active_routes' => ['products.index', 'products.show', 'products.store', 'products.update'],
                    'permission' => 'products.access',
                ],
                [
                    'title' => 'البنرات (Sliders)',
                    'icon' => 'far fa-circle',
                    'route' => 'sliders.index',
                    'active_routes' => ['sliders.*'],
                    'permission' => 'sliders.access',
                ],
            ],
        ],

        [
            'title' => 'الطلبات',
            'icon' => 'fas fa-shopping-cart',
            'type' => 'dropdown',
            'id' => 'orders-menu',
            'active_routes' => ['orders.*'],
            'permission' => 'orders.access',
            'children' => [
                [
                    'title' => 'كل الطلبات',
                    'icon' => 'fas fa-list',
                    'route' => 'orders.index',
                    'active_routes' => ['orders.index', 'orders.show'],
                    'permission' => 'orders.all',
                ],
                [
                    'title' => 'طلبات التوصيل',
                    'icon' => 'fas fa-motorcycle',
                    'route' => 'orders.delivery',
                    'active_routes' => ['orders.delivery'],
                    'permission' => 'orders.delivery',
                ],
                [
                    'title' => 'طلبات الاستلام',
                    'icon' => 'fas fa-hand-holding',
                    'route' => 'orders.pickup',
                    'active_routes' => ['orders.pickup'],
                    'permission' => 'orders.pickup',
                ],
                [
                    'title' => 'الطلبات المحلية',
                    'icon' => 'fas fa-store',
                    'route' => 'orders.local',
                    'active_routes' => ['orders.local'],
                    'permission' => 'orders.local',
                ],
                [
                    'title' => 'نقاط البيع',
                    'icon' => 'fas fa-cash-register',
                    'route' => 'pos.index',
                    'active_routes' => ['pos.*'],
                    'permission' => 'pos.access',
                ],
                [
                    'title' => 'الفواتير',
                    'icon' => 'fas fa-file-invoice-dollar',
                    'route' => 'invoices.index',
                    'active_routes' => ['invoices.*'],
                ],
                // [
                //     'title' => 'طلبات المنيو',
                //     'icon' => 'far fa-circle',
                //     'route' => 'orders.index',
                //     'active_routes' => ['orders.index'],
                //     'query' => ['source' => 'menu'],
                // ],
                // [
                //     'title' => 'طلبات نقاط البيع',
                //     'icon' => 'far fa-circle',
                //     'route' => 'orders.index',
                //     'active_routes' => ['orders.index'],
                //     'query' => ['source' => 'pos'],
                // ],
            ],
        ],

        [
            'title' => 'الأدارة',
            'icon' => 'fas fa-user-shield',
            'type' => 'dropdown',
            'id' => 'users-menu',
            'active_routes' => ['users.*', 'roles.*', 'branches.*', 'shifts.*', 'attendances.*'],
            'permission' => 'management.access',
            'children' => [
                [
                    'title' => 'المستخدمين',
                    'icon' => 'fas fa-user',
                    'route' => 'users.index',
                    'active_routes' => ['users.index', 'users.create', 'users.edit'],
                    'permission' => 'users.access',
                ],
                [
                    'title' => 'عمال التوصيل',
                    'icon' => 'fas fa-motorcycle',
                    'route' => 'delivery_men.index',
                    'active_routes' => ['delivery_men.*'],
                ],
                [
                    'title' => 'الموظفين (الكاشير)',
                    'icon' => 'fas fa-cash-register',
                    'route' => 'users.staff',
                    'active_routes' => ['users.staff'],
                ],
                [
                    'title' => 'العملاء',
                    'icon' => 'fas fa-users',
                    'route' => 'users.customers',
                    'active_routes' => ['users.customers'],
                ],
                [
                    'title' => 'الأدوار والصلاحيات',
                    'icon' => 'fas fa-key',
                    'route' => 'roles.index',
                    'active_routes' => ['roles.*'],
                    'permission' => 'roles.access',
                ],
                [
                    'title' => 'الفروع',
                    'icon' => 'fas fa-store',
                    'route' => 'branches.index',
                    'active_routes' => ['branches.*'],
                    'permission' => 'branches.access',
                ],
                [
                    'title' => 'تسجيل الحضور والانصراف',
                    'icon' => 'fas fa-clock',
                    'route' => 'attendances.index',
                    'active_routes' => ['attendances.*'],
                    'permission' => 'attendances.access',
                ],
                [
                    'title' => 'الشيفتات',
                    'icon' => 'fas fa-user-clock',
                    'route' => 'shifts.index',
                    'active_routes' => ['shifts.*'],
                    'permission' => 'shifts.access',
                ],
                [
                    'title' => 'تقرير عهدة الكاشير',
                    'icon' => 'fas fa-wallet',
                    'route' => 'cashier-cash-reports.index',
                    'active_routes' => ['cashier-cash-reports.*'],
                    'permission' => 'cashier-cash-reports.access',
                ],
            ],
        ],

        [
            'title' => 'المخزن',
            'icon' => 'fas fa-warehouse',
            'type' => 'dropdown',
            'id' => 'inventory-menu',
            'active_routes' => ['inventory.*', 'units.*'],
            'permission' => 'inventory.access',
            'children' => [
                [
                    'title' => 'الموردون',
                    'icon' => 'fas fa-truck',
                    'route' => 'inventory.suppliers.index',
                    'active_routes' => ['inventory.suppliers.*'],
                    'permission' => 'inventory.suppliers',
                ],
                [
                    'title' => 'فئات المخزون',
                    'icon' => 'fas fa-tags',
                    'route' => 'inventory.categories.index',
                    'active_routes' => ['inventory.categories.*'],
                    'permission' => 'inventory.categories',
                ],
                [
                    'title' => 'وحدات القياس',
                    'icon' => 'fas fa-balance-scale',
                    'route' => 'units.index',
                    'active_routes' => ['units.*'],
                    'permission' => 'units.access',
                ],
                [
                    'title' => 'مواد المخزن',
                    'icon' => 'fas fa-boxes',
                    'route' => 'inventory.materials.index',
                    'active_routes' => ['inventory.materials.*'],
                    'permission' => 'inventory.materials',
                ],
                [
                    'title' => 'طلبات الشراء',
                    'icon' => 'fas fa-file-alt',
                    'route' => 'inventory.purchase-requests.index',
                    'active_routes' => ['inventory.purchase-requests.*'],
                    'permission' => 'inventory.purchase_requests',
                ],
                [
                    'title' => 'أوامر الشراء',
                    'icon' => 'fas fa-shopping-cart',
                    'route' => 'inventory.purchase-orders.index',
                    'active_routes' => ['inventory.purchase-orders.*'],
                    'permission' => 'inventory.purchase_orders',
                ],
                [
                    'title' => 'الشراء / الاستلام',
                    'icon' => 'fas fa-dolly',
                    'route' => 'inventory.receipts.index',
                    'active_routes' => ['inventory.receipts.*'],
                    'permission' => 'inventory.receipts',
                ],
                [
                    'title' => 'الإنتاج',
                    'icon' => 'fas fa-industry',
                    'route' => 'inventory.production-orders.index',
                    'active_routes' => ['inventory.production-orders.*'],
                    'permission' => 'inventory.production_orders',
                ],
                [
                    'title' => 'طلبات التحويل',
                    'icon' => 'fas fa-exchange-alt',
                    'route' => 'inventory.transfer-requests.index',
                    'active_routes' => ['inventory.transfer-requests.*'],
                    'permission' => 'inventory.transfer_requests',
                ],
                [
                    'title' => 'جرد المخزن',
                    'icon' => 'fas fa-clipboard-check text-warning',
                    'route' => 'inventory.stock-counts.index',
                    'active_routes' => ['inventory.stock-counts.*'],
                    'permission' => 'inventory.stock_counts',
                ],
                [
                    'title' => 'حركات المخزون',
                    'icon' => 'fas fa-random',
                    'route' => 'inventory.movements.index',
                    'active_routes' => ['inventory.movements.*'],
                    'permission' => 'inventory.movements',
                ],
                [
                    'title' => 'لوحة المخزن',
                    'icon' => 'fas fa-chart-line',
                    'route' => 'inventory.dashboard',
                    'active_routes' => ['inventory.dashboard'],
                    'permission' => 'inventory.dashboard',
                ],
            ],
        ],

        [
            'title' => 'التقارير',
            'icon' => 'fas fa-chart-line',
            'type' => 'dropdown',
            'id' => 'reports-menu',
            'active_routes' => ['reports.*'],
            'permission' => 'reports.access',
            'children' => [
                [
                    'title' => 'المبيعات',
                    'icon' => 'far fa-circle',
                    'route' => 'reports.sales',
                    'active_routes' => ['reports.sales'],
                    'permission' => 'reports.sales',
                ],
                [
                    'title' => 'المنتجات الأكثر مبيعاً',
                    'icon' => 'far fa-circle',
                    'route' => 'reports.top-products',
                    'active_routes' => ['reports.top-products'],
                    'permission' => 'reports.top_products',
                ],
                [
                    'title' => 'أداء الموظفين',
                    'icon' => 'far fa-circle',
                    'route' => 'reports.staff-performance',
                    'active_routes' => ['reports.staff-performance'],
                    'permission' => 'reports.staff_performance',
                ],
            ],
        ],

        [
            'title' => 'الإعدادات',
            'icon' => 'fas fa-cogs',
            'type' => 'dropdown',
            'id' => 'settings-menu',
            'active_routes' => ['settings.*', 'payment-methods.*', 'tables.*', 'dining-areas.*', 'charges.*'],
            'permission' => 'settings.access',
            'children' => [
                [
                    'title' => 'الإعدادات العامة',
                    'icon' => 'far fa-circle',
                    'route' => 'settings.index',
                    'active_routes' => ['settings.index', 'settings.update'],
                    'permission' => 'settings.general',
                ],
                [
                    'title' => 'وسائل الدفع',
                    'icon' => 'far fa-circle',
                    'route' => 'payment-methods.index',
                    'active_routes' => ['payment-methods.*'],
                    'permission' => 'payment_methods.access',
                ],
                [
                    'title' => 'الطاولات والأماكن',
                    'icon' => 'far fa-circle',
                    'route' => 'tables.index',
                    'active_routes' => ['tables.*', 'dining-areas.*'],
                    'permission' => 'tables_areas.access',
                ],
                [
                    'title' => 'الضرائب والرسوم',
                    'icon' => 'far fa-circle',
                    'route' => 'charges.index',
                    'active_routes' => ['charges.*'],
                    'permission' => 'charges.access',
                ],
            ],
        ],
    ],

    // Cashier
    'cashier' => [
        [
            'title' => 'نقطة البيع',
            'icon' => 'fas fa-cash-register',
            'route' => 'pos.index',
            'active_routes' => ['pos.*'],
            'permission' => 'pos.access',
        ],
        [
            'title' => 'الطلبات',
            'icon' => 'fas fa-shopping-cart',
            'type' => 'dropdown',
            'id' => 'cashier-orders-menu',
            'active_routes' => ['orders.*', 'invoices.*'],
            'permission' => 'orders.access',
            'children' => [
                [
                    'title' => 'كل الطلبات',
                    'icon' => 'fas fa-list',
                    'route' => 'orders.index',
                    'active_routes' => ['orders.index', 'orders.show'],
                    'permission' => 'orders.all',
                ],
                [
                    'title' => 'طلبات التوصيل',
                    'icon' => 'fas fa-motorcycle',
                    'route' => 'orders.delivery',
                    'active_routes' => ['orders.delivery'],
                    'permission' => 'orders.delivery',
                ],
                [
                    'title' => 'طلبات الاستلام',
                    'icon' => 'fas fa-hand-holding',
                    'route' => 'orders.pickup',
                    'active_routes' => ['orders.pickup'],
                    'permission' => 'orders.pickup',
                ],
                [
                    'title' => 'الطلبات المحلية',
                    'icon' => 'fas fa-store',
                    'route' => 'orders.local',
                    'active_routes' => ['orders.local'],
                    'permission' => 'orders.local',
                ],
                [
                    'title' => 'الفواتير',
                    'icon' => 'fas fa-file-invoice-dollar',
                    'route' => 'invoices.index',
                    'active_routes' => ['invoices.*'],
                ],
            ],
        ],
        [
            'title' => 'الشيفتات',
            'icon' => 'fas fa-user-clock',
            'route' => 'shifts.index',
            'active_routes' => ['shifts.*'],
            'permission' => 'shifts.access',
        ],
    ],
];
